photo_dir: "photos"
temp_dir: "/tmp"
parallel:
  workers: 8
photo_purge: False
sync_timeout: 120
master_wait_for: 90

database:
  file: "sqlite.db"
  photo_table: "photo"
  face_table: "face"
  bib_table: "bib"

logging:
  level: "DEBUG"
  dir: "logs"
  scan_prefix: "scan"
  get_prefix: "get"
  screen_print: True

deepface:
  detector: "mtcnn"
  alignment: True
  model: "Facenet512"
  use_gpu: True
  debug: True
  expand_percentage: 5
  debug_dir: "face_debug"
  detect_confidence: 0.3

ocr:
  use_gpu: True
  debug: True
  debug_dir: "ocr_debug"
  min_size: 3
  max_size: 5
  confidence: 0.3

search:
  face_match_confidence: 0.8
  face_detect_confidence: 0.70
  similarity_metric: "cosine"
  bib_confidence: 0.75
