photo_dir: "data"
temp_dir: "/tmp"
parallel:
  workers: 1
photo_purge: False
sync_timeout: 120
master_wait_for: 90

database:
  host: localhost
  port: 5432
  username: mphoto_user
  password: mphoto
  database: mphoto_db
  default_search_limit: 100

table_names:
  event: event
  bib: bib
  download_history: download_history
  photo: photo
  bib_photo: bib_photo
  face_photo: face_photo

web:
  port: 8080
  host: 0.0.0.0

logging:
  level: "DEBUG"
  dir: "logs"
  scan_prefix: "scan"
  get_prefix: "search"
  web_prefix: "web"
  screen_print: True
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

deepface:
  detector: "mtcnn"
  alignment: True
  model: "Facenet512"
  use_gpu: True
  debug: True
  expand_percentage: 5
  debug_dir: "face_debug"
  detect_confidence: 0.3
  embedding_dim: 512

ocr:
  use_gpu: True
  debug: True
  debug_dir: "ocr_debug"
  min_size: 3
  max_size: 5
  confidence: 0.3

search:
  face_similarity: 0.8
  face_detect_confidence: 0.70
  bib_confidence: 0.75
